### ISSUE TITLE
Expose features of surf

### ISSUE THREAD

**Issue by IgnisDa** [06chaynes/surf-retry#1]
Hello! I am unable to use this project in mine because all default features of surf are pulled in. Here is what I have:

https://github.com/IgnisDa/ryot/blob/788b9a4dc9187ef8c9790e1549d887e058f5e656/apps/backend/Cargo.toml#L68-L70

Would it be possible to expose these features?

**Comment by 06chaynes** [comment]
I can set default-features = false, I think this would resolve this correct?

**Comment by 06chaynes** [comment]
went ahead and published a new version with these changes, please let me know if you have any issues!
